import type { NextPage } from 'next'
import { i18n } from 'next-i18next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import MainLayout from '../Layout/MainLayout'
import Navbar from '../../components/Navbar'
// import PostsList from '../Post/postsList'
import TopMenu from '../../components/TopMenu'
import { RootState } from '../../store'
import { changeTheme } from '../../store/reducers/themeReducer'
import PostsListInfinity from '../Post/postsListInfinity'
import {
  onHasNextPage,
  onIsNextPageLoading,
  onSetItems,
} from '../../store/reducers/postsReducer'
import { generateIds } from '../../utilize/generateIds'

const mockPosts = {
  id: '1',
  postType: 'post',
  user: {
    userName: 'News Update',
    userId: '99123223432',
    userAvatar: 'test',
    userSlug: '@newsofficial',
  },
  counts: {
    like: 123,
    comments: 342,
    repost: 34,
  },
  post: {
    postContent:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    postDate: '2021-12-25T10:05:46.384Z',
  },
  isLiked: false,
}

const Home: NextPage = (props) => {
  const dispatch = useDispatch()
  const store = useSelector((state: RootState) => state)
  const theme = store.theme
  const postsStore = store.posts
  const topMenuStore = store.topMenu
  const items = postsStore.items

  // Callback when scroll to bottom.
  const loadNextPage = (startPage: number, endPage: number) => {
    // console.log('loadNextPage', startPage, endPage)
    setTimeout(() => {
      dispatch(onHasNextPage(items.length < 50))
      dispatch(onIsNextPageLoading(false))
      const pollData: any = new Array(10).fill(items.length).map((v) => {
        const createData = { ...mockPosts }
        createData.id = generateIds()
        v = createData
        return v
      })
      const pollDataMerge = [...items].concat(pollData)
      dispatch(onSetItems(pollDataMerge))
    }, 500)
  }

  // Handle when tab change
  useEffect(() => {
    console.log('Tab changed.')
  }, [topMenuStore.activeTab])

  return (
    <MainLayout {...props}>
      <Head>
        <title>BroTalks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        {theme.isNavbar && <Navbar />}
        <div className="mt-16">
          <TopMenu />
        </div>
      </div>
      <main>
        <div id="posts-content" className="posts-content z-0">
          {/* <PostsList /> */}
          <PostsListInfinity
            hasNextPage={postsStore.hasNextPage}
            isNextPageLoading={postsStore.isNextPageLoading}
            items={items}
            loadNextPage={loadNextPage}
          />
        </div>
      </main>
    </MainLayout>
  )
}

export default Home
